/**
 * Mobile data layer — reads directly from Supabase using the authenticated
 * client. RLS scopes every query to the signed-in user (auth.uid() = user_id),
 * so these return only the current user's real rows. No demo content.
 */
import { supabase } from "./supabase";

export type ContentStatus = "draft" | "published" | "archived";
export type ContentSource = "recording" | "text" | "video" | "podcast";

export interface ContentRow {
  id: string;
  title: string;
  category: string | null;
  tags: string[];
  notes: string | null;
  body: string | null;
  scheduled_at: string | null;
  created_at: string;
  status?: ContentStatus | null;
  source?: ContentSource | null;
  excerpts?: Record<string, string> | null;
}

export interface LinkPreview {
  title?: string;
  description?: string;
  image?: string;
  favicon?: string;
  site_name?: string;
  author?: string;
  url?: string;
  platform?: string;
  type?: "link" | "youtube" | "twitter";
}

export interface IdeaRow {
  id: string;
  title: string;
  content: string | null;
  url: string | null;
  source_type: string | null;
  tags: string[];
  pillar: string | null;
  preview: LinkPreview | null;
  created_at: string;
}

export interface PersonaProfile {
  positioning_statement?: string;
  pillars?: { title: string; description?: string }[];
  voice_profile?: string[];
  tone?: { style?: string; voice?: string; formality?: string; humor?: string };
  demographics?: { industry?: string; role?: string; experience?: string };
  subscription?: { active?: boolean; plan?: string; mock?: boolean };
  /** ISO date of the last persona edit — enforces the once-a-month change rule. */
  persona_changed_at?: string;
  // Full strategy (generated by analyze-persona)
  linkedin_url?: string;
  purpose?: string;
  topics?: string[];
  audience?: string;
  values?: string[];
  professional_background?: string;
  differentiation?: { do?: string[]; dont?: string[] };
  sample_post?: string;
  suggested_platforms?: string[];
  cadence?: string;
}

/** True when the user has an active (incl. mock) Pro subscription. */
export async function isProUser(): Promise<boolean> {
  try {
    const p = await getPersona();
    return !!p?.profile?.subscription?.active;
  } catch {
    return false;
  }
}

export interface PersonaRow {
  name: string;
  description: string | null;
  profile: PersonaProfile | null;
  onboarding_complete: boolean;
}

export async function updateContent(
  id: string,
  patch: Partial<Pick<ContentRow, "title" | "category" | "body" | "scheduled_at" | "status">>
): Promise<void> {
  const { error } = await supabase.from("content").update(patch).eq("id", id);
  if (error) throw error;
}

/** Set the publish/archive status of a content entry. */
export async function setContentStatus(id: string, status: ContentStatus): Promise<void> {
  const { error } = await supabase.from("content").update({ status }).eq("id", id);
  if (error) throw error;
}

/** Persist generated platform posts on the content row (cross-device sync). */
export async function setContentExcerpts(id: string, excerpts: Record<string, string>): Promise<void> {
  const { error } = await supabase.from("content").update({ excerpts }).eq("id", id);
  if (error) throw error;
}

export async function deleteContent(id: string): Promise<void> {
  const { error } = await supabase.from("content").delete().eq("id", id);
  if (error) throw error;
}

export async function listContent(): Promise<ContentRow[]> {
  const { data, error } = await supabase
    .from("content")
    .select("*")
    .order("created_at", { ascending: false })
    .limit(50);
  if (error) throw error;
  return (data ?? []) as ContentRow[];
}

export async function listIdeas(): Promise<IdeaRow[]> {
  const { data, error } = await supabase
    .from("ideas")
    .select("*")
    .order("created_at", { ascending: false })
    .limit(50);
  if (error) throw error;
  return (data ?? []) as IdeaRow[];
}

export async function createIdea(input: {
  title: string;
  content?: string;
  url?: string;
  source_type?: string;
  tags?: string[];
  preview?: LinkPreview;
}): Promise<IdeaRow> {
  const { data: userData } = await supabase.auth.getUser();
  const { data, error } = await supabase
    .from("ideas")
    .insert({
      user_id: userData.user?.id,
      title: input.title,
      content: input.content ?? null,
      url: input.url ?? null,
      source_type: input.source_type ?? null,
      tags: input.tags ?? [],
      preview: input.preview ?? null,
    })
    .select()
    .single();
  if (error) throw error;
  return data as IdeaRow;
}

export async function deleteIdea(id: string): Promise<void> {
  const { error } = await supabase.from("ideas").delete().eq("id", id);
  if (error) throw error;
}

export async function updateIdea(
  id: string,
  patch: Partial<Pick<IdeaRow, "title" | "content" | "tags">>
): Promise<void> {
  const { error } = await supabase.from("ideas").update(patch).eq("id", id);
  if (error) throw error;
}

/** Save the user's content pillars into persona.profile (upsert, RLS-scoped). */
export async function savePillars(pillars: { title: string; description?: string }[]): Promise<void> {
  const { data: userData } = await supabase.auth.getUser();
  const uid = userData.user?.id;
  if (!uid) throw new Error("Oturum yok");
  const current = await getPersona();
  const profile = { ...(current?.profile ?? {}), pillars };
  const { error } = await supabase
    .from("personas")
    .upsert(
      {
        user_id: uid,
        name: current?.name || "Profilim",
        profile,
        onboarding_complete: current?.onboarding_complete ?? false,
      },
      { onConflict: "user_id" }
    );
  if (error) throw error;
}

/** Merge a patch into persona.profile and upsert (RLS-scoped). Accepts extra
 *  keys too (AI-generated profiles carry fields beyond our typed subset). */
export async function savePersonaProfile(patch: Partial<PersonaProfile> & Record<string, unknown>): Promise<void> {
  const { data: userData } = await supabase.auth.getUser();
  const uid = userData.user?.id;
  if (!uid) throw new Error("Oturum yok");
  const current = await getPersona();
  const profile = { ...(current?.profile ?? {}), ...patch };
  const { error } = await supabase
    .from("personas")
    .upsert(
      {
        user_id: uid,
        name: current?.name || "Profilim",
        profile,
        onboarding_complete: current?.onboarding_complete ?? false,
      },
      { onConflict: "user_id" }
    );
  if (error) throw error;
}

export async function getPersona(): Promise<PersonaRow | null> {
  const { data, error } = await supabase
    .from("personas")
    .select("name, description, profile, onboarding_complete")
    .limit(1)
    .maybeSingle();
  if (error) throw error;
  return (data as PersonaRow) ?? null;
}

/** Save a generated draft to the user's Content (direct insert, RLS-scoped). */
export async function saveContent(input: {
  title: string;
  body?: string;
  category?: string;
  scheduled_at?: string | null;
  source?: ContentSource;
  excerpts?: Record<string, string>;
}): Promise<ContentRow> {
  const { data: userData } = await supabase.auth.getUser();
  const userId = userData.user?.id;
  const row: Record<string, unknown> = {
    user_id: userId,
    title: input.title,
    body: input.body ?? null,
    category: input.category ?? null,
    scheduled_at: input.scheduled_at ?? null,
  };
  // Only set source when provided so inserts still work pre-migration.
  if (input.source) row.source = input.source;
  // Platform excerpts — X/LinkedIn/Substack/Medium çıktıları kalıcılaştır
  if (input.excerpts && Object.keys(input.excerpts).length > 0) {
    row.excerpts = input.excerpts;
  }
  const { data, error } = await supabase
    .from("content")
    .insert(row)
    .select()
    .single();
  if (error) throw error;
  return data as ContentRow;
}

const TR_MONTHS = ["Oca", "Şub", "Mar", "Nis", "May", "Haz", "Tem", "Ağu", "Eyl", "Eki", "Kas", "Ara"];

/** "17 Haz" style short Turkish date. */
export function formatShortDate(iso: string): string {
  const d = new Date(iso);
  if (isNaN(d.getTime())) return "";
  return `${d.getDate()} ${TR_MONTHS[d.getMonth()]}`;
}
